# Generated by Django 6.1 on 2026-08-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_bids_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
