# Generated by Django 6.1 on 2026-08-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_category_category_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
